#ifndef HARDWAREPROFILE_H_INCLUDED
#define HARDWAREPROFILE_H_INCLUDED

#include <xc.h>
#include "system.h"

#define TRIS_OUTPUT 0
#define TRIS_INPUT  1

#define BUZZER_TRIS TRISAbits.TRISA14
#define BUZZER_LAT  LATAbits.LATA14

#define SPI_MOSI_TRIS TRISCbits.TRISC5
#define SPI_MOSI_LAT LATCbits.LATC5
#define SPI_CLK_TRIS TRISCbits.TRISC4
#define SPI_CLK_LAT LATCbits.LATC4
#define SPI_MISO_TRIS TRISAbits.TRISA1
#define SPI_MISO_PORT PORTAbits.RA1
#define SPI_CS1_TRIS TRISAbits.TRISA0
#define SPI_CS1_LAT LATAbits.LATA0
#define LCD_D_TRIS TRISCbits.TRISC3
#define LCD_D_LAT LATCbits.LATC3
#define LCD_RESET_TRIS TRISAbits.TRISA9
#define LCD_RESET_LAT LATAbits.LATA9
#define LCD_CS_D_TRIS TRISAbits.TRISA4
#define LCD_CS_D_LAT LATAbits.LATA4

#define RELE5_TRIS TRISAbits.TRISA8
#define RELE5_LAT LATAbits.LATA8
#define RELE4_TRIS TRISAbits.TRISA3
#define RELE4_LAT LATAbits.LATA3
#define RELE3_TRIS TRISAbits.TRISA2
#define RELE3_LAT LATAbits.LATA2
#define RELE2_TRIS TRISAbits.TRISA13
#define RELE2_LAT LATAbits.LATA13

#define KEYBOARD_RIGA1_TRIS TRISCbits.TRISC1
#define KEYBOARD_RIGA1_LAT LATCbits.LATC1
#define KEYBOARD_RIGA2_TRIS TRISCbits.TRISC0
#define KEYBOARD_RIGA2_LAT LATCbits.LATC0
#define KEYBOARD_RIGA3_TRIS TRISBbits.TRISB3
#define KEYBOARD_RIGA3_LAT LATBbits.LATB3
#define KEYBOARD_COL1_TRIS TRISBbits.TRISB0
#define KEYBOARD_COL1_PORT PORTBbits.RB0
#define KEYBOARD_COL2_TRIS TRISBbits.TRISB1
#define KEYBOARD_COL2_PORT PORTBbits.RB1
#define KEYBOARD_COL3_TRIS TRISBbits.TRISB2
#define KEYBOARD_COL3_PORT PORTBbits.RB2

// ingressi
#define IN7_TRIS TRISBbits.TRISB8
#define IN7_PORT PORTBbits.RB8
#define IN6_TRIS TRISBbits.TRISB9
#define IN6_PORT PORTBbits.RB9
#define IN5_TRIS TRISCbits.TRISC6
#define IN5_PORT PORTCbits.RC6
#define IN4_TRIS TRISCbits.TRISC7
#define IN4_PORT PORTCbits.RC7
#define IN3_TRIS TRISCbits.TRISC8
#define IN3_PORT PORTCbits.RC8
#define IN2_TRIS TRISCbits.TRISC9
#define IN2_PORT PORTCbits.RC9
#define IN1_TRIS TRISAbits.TRISA11
#define IN1_PORT PORTAbits.RA11

//eeprom i2c
#define I2C_CLK_TRIS TRISAbits.TRISA7
#define I2C_CLK LATAbits.LATA7
#define I2C_DATA_TRIS TRISAbits.TRISA10
#define I2C_DATA_OUT LATAbits.LATA10
#define I2C_DATA_IN PORTAbits.RA10
#define WRITE_PROTECT_TRIS TRISAbits.TRISA12
#define WRITE_PROTECT LATAbits.LATA12

//analogico
#define PTC_CHANNEL 8
#define PTC_TRIS TRISBbits.TRISB12

//interrupt
#define INT0_TRIS TRISBbits.TRISB7
#define INT0_PORT PORTBbits.RB7

//gettoniera
#define GETT_TRIS TRISBbits.TRISB13
#define GETT_PORT (!PORTBbits.RB13)

//uart
#define  UART_RX_TRIS TRISBbits.TRISB15
#define  UART_TX_TRIS TRISBbits.TRISB14

#endif
